package com.myspace.poc_upload_doc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class dadoUpload implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String nomedocumento;
	private java.lang.String documents;

	public dadoUpload() {
	}

	public java.lang.String getNomedocumento() {
		return this.nomedocumento;
	}

	public void setNomedocumento(java.lang.String nomedocumento) {
		this.nomedocumento = nomedocumento;
	}

	public java.lang.String getDocuments() {
		return this.documents;
	}

	public void setDocuments(java.lang.String documents) {
		this.documents = documents;
	}

	public dadoUpload(java.lang.String nomedocumento, java.lang.String documents) {
		this.nomedocumento = nomedocumento;
		this.documents = documents;
	}

}